title: Manti
logo: /assets/img/logo.jpg
description: 🎮 Game Dev. VR, video games, and tech? More like my life's passion. Or obsession. Anyway.. 🚀💾
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
